import 'package:first_design/models/agent_model.dart';
import 'package:first_design/models/maps_model.dart';
import 'package:first_design/models/weapons_model.dart';
import 'package:first_design/screens/agents_tab.dart';
import 'package:first_design/screens/maps_tab.dart';
import 'package:first_design/screens/weapons_tab.dart';
import 'package:first_design/services/apis/api_manager.dart';
import 'package:first_design/services/apis/api_maps.dart';
import 'package:first_design/services/apis/api_weapons.dart';
import 'package:first_design/widgets/category_botton.dart';
import 'package:flutter/material.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  int selectedIndex = 0;
  late Future<AgentModel> _agentsFuture;
  late Future<Autogenerated> _mapsFuture;
  late Future<Weapons> _weaponsFuture;

  @override
  void initState() {
    super.initState();
    _agentsFuture = ApiManager().getAgents();
    _mapsFuture = ApiMaps().getMaps();
    _weaponsFuture = ApiWeapons().getWeapons();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xff06111C),
      body: Padding(
        padding: const EdgeInsets.all(20.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const SizedBox(height: 10),
            Center(
              child: Image.asset('assets/images/Logo Icon (2).png'),
            ),
            const SizedBox(height: 10),
            Center(
              child: Image.asset('assets/images/Logo Text.png'),
            ),
            const SizedBox(height: 15),
            SizedBox(
              height: 45,
              child: ListView(
                scrollDirection: Axis.horizontal,
                children: [
                  const SizedBox(
                    width: 200.0,
                  ),
                  CategoryButton(
                    text: 'Agents',
                    isSelected: selectedIndex == 0,
                    onPressed: () {
                      setState(() {
                        selectedIndex = 0;
                      });
                    },
                  ),
                  const SizedBox(
                    width: 40.0,
                  ),
                  CategoryButton(
                    text: 'Maps',
                    isSelected: selectedIndex == 1,
                    onPressed: () {
                      setState(() {
                        selectedIndex = 1;
                      });
                    },
                  ),
                  const SizedBox(
                    width: 40.0,
                  ),
                  CategoryButton(
                    text: 'Weapons',
                    isSelected: selectedIndex == 2,
                    onPressed: () {
                      setState(() {
                        selectedIndex = 2;
                      });
                    },
                  ),
                ],
              ),
            ),
            // const SizedBox(height: 10),
            Expanded(
              child: selectedIndex == 0
                  ? AgentsTab(agentsFuture: _agentsFuture)
                  : selectedIndex == 1
                      ? MapsTab(mapsFuture: _mapsFuture)
                      : WeaponsTab(weaponsFuture: _weaponsFuture),
            ),
          ],
        ),
      ),
    );
  }
}
