import 'package:cached_network_image/cached_network_image.dart';
import 'package:first_design/models/maps_model.dart';
import 'package:flutter/material.dart';

class MapsTab extends StatelessWidget {
  final Future<Autogenerated> mapsFuture;

  const MapsTab({Key? key, required this.mapsFuture}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Autogenerated>(
      future: mapsFuture,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError) {
          return Center(child: Text('Error: ${snapshot.error}'));
        }
        if (!snapshot.hasData || snapshot.data?.data == null) {
          return const Center(child: Text('No maps found.'));
        } else {
          var maps = snapshot.data?.data ?? [];
          return ListView.builder(
            itemCount: maps.length,
            itemBuilder: (context, index) {
              var map = maps[index];
              return Stack(
                children: [
                  Card(
                    elevation: 5,
                    margin: const EdgeInsets.symmetric(vertical: 10),
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(10),
                      child: Container(
                        height: 200,
                        child: CachedNetworkImage(
                          imageUrl: map.splash ?? '',
                          height: 150.0,
                          width: double.infinity,
                          fit: BoxFit.cover,
                          placeholder: (context, url) =>
                              Center(child: CircularProgressIndicator()),
                          errorWidget: (context, url, error) => Image.asset(
                            'assets/images/monitor-1350918_640.webp',
                            fit: BoxFit.cover,
                            width: double.infinity,
                          ),
                        ),
                      ),
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Text(
                      map.displayName ?? '',
                      style: const TextStyle(
                        fontSize: 25.0,
                        fontWeight: FontWeight.bold,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ],
              );
            },
          );
        }
      },
    );
  }
}
